{{- if .Values.hcloud.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.hcloud.namespace | default "hcloud" }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
  annotations:
    {{- include "template.annotations" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hcloud
  labels:
    {{- include "template.labels" . | nindent 4 }}
  annotations:
    {{- include "template.annotations" . | nindent 4 }}
data:
  token: {{ .Values.hcloud.token | b64enc }}
{{- end }}