apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: kubelet
spec:
  nodeSelector:
    # apply to all nodes
    matchLabels: {}
  ingress:
    # prometheus -> kubelet
    - fromEndpoints:
        - matchLabels:
            app: kube-prometheus-stack-prometheus
      toPorts:
        - ports:
            - port: '10250'
              protocol: TCP
    # api server -> kubelet
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: '10250'
              protocol: TCP
