apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: kubelet
spec:
  nodeSelector:
    # apply to all nodes
    matchLabels: {}
  ingress:
    # prometheus -> kubelet
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: prometheus-kube-prometheus-prometheus
            io.kubernetes.pod.namespace: observability
      toPorts:
        - ports:
            - port: '10250'
              protocol: TCP
    # api server -> kubelet
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: '10250'
              protocol: TCP
