{{- if .Values.vault.enabled -}}
{{- range .Values.vault.applicationNamespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-service-principal
  namespace: {{ .name }}
data:
  clientID: {{ $.Values.vault.clientId | b64enc }}
  clientSecret: {{ $.Values.vault.clientSecret | b64enc }}
{{- end }}
{{- end }}