{{- if .Values.vault.enabled -}}
{{- range .Values.vault.applicationNamespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vault-service-principal
  namespace: {{ .name }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  clientID: {{ $.Values.vault.clientId | b64enc }}
  clientSecret: {{ $.Values.vault.clientSecret | b64enc }}
{{- end }}
{{- end }}