apiVersion: v2
name: wahlrecht
description: Installs the Wahlrecht API into the Kubernetes cluster
type: application
version: 0.3.0
maintainers:
  - name: Jim Martens
    url: https://2martens.de
sources:
  - https://git.2martens.de/2martens/wahlrecht
dependencies:
  - name: template
    version: 0.4.0
    repository: file://../template
annotations:
  artifacthub.io/images: |
    - name: 2martens/wahlrecht:latest
      image: 2martens/wahlrecht:latest
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/changes: |
    - kind: changed
      description: Use restrictive security context by default
  artifacthub.io/signKey: |
    fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
    url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
  artifacthub.io/prerelease: true
