{{- if .Values.cilium.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hubble-relay
  namespace: kube-system
specs:
  - endpointSelector:
      # apply to hubble relay pods
      matchLabels:
        io.cilium.k8s.policy.serviceaccount: hubble-relay
    ingress:
      # kubelet -> hubble relay probes
      - fromEntities:
          - host
        toPorts:
          - ports:
              - port: '4245'
                protocol: TCP
    egress:
      # hubble relay -> hubble agent
      - toEntities:
          - host
          - remote-node
        toPorts:
          - ports:
              - port: '4244'
                protocol: TCP
      - toEntities:
          - world
        toPorts:
          - ports:
              - port: '443'
                protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hubble-relay
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: hubble-relay
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              k8s-app: hubble-ui
      ports:
        - port: '80'
          protocol: TCP
        - port: '4245'
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: '53'
          protocol: UDP
{{- end }}