---
- name: List domains
  ansible.builtin.command: uberspace web domain list
  changed_when: false
  register: domains
- name: Set up domain
  when: domains.stdout.find(frontend_domain) == -1
  block:
    - name: Add domain
      ansible.builtin.command: uberspace web domain add {{ frontend_domain }}
      register: new_domain
      changed_when: true
    - name: Print out important information
      changed_when: false
      ansible.builtin.debug:
        msg: "{{ new_domain.stdout }}"
