apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - port: 9963
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: 9964
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-agent
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: 9965
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble