image:
  repository: 2martens/timetable

ingress:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  tls:
    - secretName: chart-example-tls
      hosts:
        - chart-example.local

application:
  port: 12100
  actuatorPort: 12101
  keycloak:
    url: https://id.2martens.de
    realm: 2martens
  configserver:
    scheme: http
    host: configserver
    port: 8888
    prefix: /config
  kafka:
    host: kafka
    port: 9092

service:
  port: 12100
  actuatorPort: 12101

secrets:
  # Needs to be overwritten. Will be ignored if vault is enabled.
  MONGODB_CONNECTION_STRING: ""
  # Needs to be overwritten. Will be ignored if vault is enabled.
  CLIENT_SECRET: ""

environment:
  - name: PORT
    value: "{{ .Values.application.port }}"
  - name: ACTUATOR_PORT
    value: "{{ .Values.application.actuatorPort }}"
  - name: KEYCLOAK_URL
    value: "{{ .Values.application.keycloak.url }}"
  - name: KEYCLOAK_REALM
    value: "{{ .Values.application.keycloak.realm }}"
  - name: CONFIGSERVER_SCHEME
    value: "{{ .Values.application.configserver.scheme }}"
  - name: CONFIGSERVER_HOST
    value: "{{ .Values.application.configserver.host }}"
  - name: CONFIGSERVER_PORT
    value: "{{ .Values.application.configserver.port }}"
  - name: CONFIGSERVER_PREFIX
    value: "{{ .Values.application.configserver.prefix }}"
  - name: KAFKA_HOST
    value: "{{ .Values.application.kafka.host }}"
  - name: KAFKA_PORT
    value: "{{ .Values.application.kafka.port }}"
