apiVersion: v2
name: kafka
description: Simple Kafka chart to get started
type: application
version: 0.1.4
maintainers:
  - name: Jim Martens
    url: https://2martens.de
dependencies:
  - name: prometheus-kafka-exporter
    version: 2.7.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: template
    version: 0.1.20
    repository: file://../template
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added Prometheus support
  artifacthub.io/signKey: |
    fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
    url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
  artifacthub.io/prerelease: true
