image:
  repository: confluentinc/cp-kafka
  tag: latest
application:
  port: &applicationPort 9092
  isSpring: false
  zookeeper:
    host: zookeeper
    port: 2181
service:
  port: *applicationPort
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
environment:
  - name: KAFKA_BROKER_ID
    value: "1"
  - name: KAFKA_ZOOKEEPER_CONNECT
    value: "{{ .Values.application.zookeeper.host }}:{{ .Values.application.zookeeper.port }}"
  - name: KAFKA_LISTENERS
    value: "PLAINTEXT://0.0.0.0:{{ .Values.application.port }}"
  - name: KAFKA_ADVERTISED_LISTENERS
    value: "PLAINTEXT://kafka:{{ .Values.application.port }}"
  - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
    value: PLAINTEXT:PLAINTEXT
  - name: KAFKA_INTER_BROKER_LISTENER_NAME
    value: PLAINTEXT
  - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
    value: "1"
prometheus:
  enabled: false
volumes:
  - name: kafka
    emptyDir:
      medium: Memory
  - name: log
    emptyDir:
      medium: Memory
volumeMounts:
  - mountPath: /etc/kafka
    name: kafka
  - mountPath: /var/log/kafka
    name: log
