{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  {{- if .ignoreDifferences }}
  ignoreDifferences:
    {{- range .ignoreDifferences }}
    - group: {{ .group }}
      kind: {{ .kind }}
      name: {{ .name }}
      namespace: {{ .namespace }}
      jsonPointers:
        {{- toYaml .jsonPointers . | nindent 10 }}
    {{- end }}
  {{- end }}
  syncPolicy:
    {{- if .serverSideApply }}
    syncOptions:
      - ServerSideApply=true
    {{- end }}
    automated:
      prune: true
  destination:
    namespace: {{ .namespace }}
    server: {{ $.Values.overall.destinationServer }}
  project: {{ .project }}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
    {{- if .repoURL | contains "chart" }}
    chart: {{ .chart | default .name }}
    {{- else }}
    path: argocd/{{ .name }}/{{ $.Values.overall.environment }}
    {{- end }}
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - argocd_values.yaml
{{- end }}
