kube-prometheus-stack:
  nameOverride: observability-prometheus
  prometheusOperator:
    admissionWebhooks:
      certManager:
        enabled: true
#        issuerRef:
#          name: "lets-encrypt"
#          kind: "ClusterIssuer"
  prometheus-node-exporter:
    hostRootFsMount:
      mountPropagation: None

  alertmanager:
    enabled: true
  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: lets-encrypt
        ingress.kubernetes.io/rewrite-target: /
      hosts:
        - grafana.k8s.monitoring.2martens.de
      tls:
        - secretName: grafana-general-tls
          hosts:
            - grafana.k8s.monitoring.2martens.de

  prometheus:
    prometheusSpec:
      retention: 6h
      disableCompaction: true
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: hcloud-volumes
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10Gi
      thanos:
        objectStorageConfig:
          existingSecret:
            key: thanos.yaml
            name: thanos-object-storage-config
    ingress:
      enabled: false
    thanosServiceMonitor:
      enabled: true
    thanosService:
      enabled: true
  kubeControllerManager:
    endpoints:
      - 10.0.0.7
  kubeScheduler:
    endpoints:
      - 10.0.0.7
storage:
  handles:
    - "100341703"