apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-without-secrets-2martens
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 2martens
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-without-secrets
