apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: 2martens
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dEQ0NBVUFDQVFBd0V6RVJNQThHQTFVRUF3d0lNbTFoY25SbGJuTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGV6dEgzQWlhNmJpMmxzMGtIQW5LUDhOUFpWTDlJVldrdnJGS0N3UmZuClRPSnM5Z0dCWmxzbnl4WEl6Y2xBeUFjbzI2d2pKanNKZkUybVFSYlZ0alNqOERORklNeVZsdVloUDRyQS9yYlMKYmFzbEMrTUR1TGh3VGhFRi82UkpaMENudmdGSkc1bUZkbmx0WjdGSDZGTkdPalZWVktxc2FTL0ZRdjE4S0g4NwpabVNmRHdqS3pla2FZSFZyL3F3ZmFLSmpXSm1jd0JhRkw0VGcwcHJrVzBIWm5QTUZVclFFcXM4WEpnekRGQ2xNCkRwRXM1ZDdXYjd0b2Q0K2E4dE80UWFheXB2ZHdUOUc5YWd5QUYyUnNoMmhRakZCSXFtLzkwV2RRM0tGRmI1ZGQKR1l6YmcycnRJR21xb0x3NGxFYXRQU3lPM2lVTnh3MWNidU9tcHlQTnI1aWxBZ01CQUFHZ0FEQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBa3FpMllqU2wzaVRiTXVSa2xRQVRBck5xQWFmaXZXSHJCdVlsdEhTeEFlNDB5aDR6Ci9MOExHQisyREZORmpvTWFIY1ZpdHJMTDRKeGlRay9jSEs5ZW1JdjZNWFpGK3lUa0ZQYkVOeWowZFU3VVBObisKcE1zT1ViRkpKdGsybmJ4Q3JSdkE0ZSt4T2ZHVllxKzdhdS94ZTVvbFBDanVZeWM2UnNiQkRxcDRnbFZzSzUydwp3Vit6Z29QYWpmV05oYnphUDlYZ0dSWVM5RzlrcDJwNEVrbU9OOUltTnJvUjBTbkhSWG1PbllsQlJCY0p0RHhmCmladjI3OFlaQ095cEFOZmtlYThCUU12YWNPbDcwRVlOMnFMbTB5alo5VW5LN1ZuL00wcW5pKy9Wc3hYT1dqc3IKNzNNWHlWdGUzQlUycHUyM3pGQ1doVm83SUt0bmZseHFJbnlyQnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  usages:
    - digital signature
    - key encipherment
    - client auth