apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: NAME
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
    - system:authenticated
  request: BASE64_CSR
  usages:
    - digital signature
    - key encipherment
    - client auth