apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shell-access-127001
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 127.0.0.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shell-access
