---
- name: Install drone cli
  block:
    - name: Download drone cli
      ansible.builtin.get_url:
        url: https://github.com/drone/drone-cli/releases/download/{{ drone_cli_version }}/drone_linux_{{ architecture }}.tar.gz
        dest: /home/{{ ssh_user }}/drone_linux_{{ architecture }}.tar.gz
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "644"
    - name: Unpack the cli archive
      ansible.builtin.unarchive:
        dest: /home/{{ ssh_user }}
        src: /home/{{ ssh_user }}/drone_linux_{{ architecture }}.tar.gz
        remote_src: true
      register: drone_unpack
    - name: Install drone cli
      ansible.builtin.command:
        cmd: install -t /usr/local/bin /home/{{ ssh_user }}/drone
      changed_when: true
