apiVersion: v2
name: configserver
version: 0.1.21
type: application
description: "Minimal Spring Boot config server"
maintainers:
  - name: Jim Martens
    url: https://2martens.de
sources:
  - https://git.2martens.de/2martens/config-server
dependencies:
  - name: template
    version: 0.1.20
    repository: file://../template
annotations:
  artifacthub.io/images: |
    - name: 2martens/configserver:latest
      image: 2martens/configserver:latest
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/changes: |
    - kind: changed
      description: Added support for prometheus operator
  artifacthub.io/signKey: |
    fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
    url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
  artifacthub.io/prerelease: true
