apiVersion: v2
name: configserver
version: 0.1.5
type: application
description: "Minimal Spring Boot config server"
maintainers:
  - name: Jim Martens
    url: https://2martens.de
sources:
  - https://git.2martens.de/2martens/config-server
dependencies:
  - name: template
    version: 0.1.9
    repository: https://repo.2martens.de/charts
annotations:
  artifacthub.io/images: |
    - name: configserver
      image: 2martens/configserver:latest
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/changes: |
    - kind: added
      description: Completed README to contain all steps required to jumpstart an application chart
    - kind: added
      description: Added sign key entry to make verifying easier
    - kind: added
      description: Added the changelog
  artifacthub.io/signKey: |
    fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
    url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
