image:
  repository: 2martens/configserver
  tag: 0.1.17

application:
  port: &applicationPort 8888
  actuatorPort: &actuatorPort 13000
  prefix: /config
  repositoryPath: "https://git.2martens.de/2martens/{application}"
  searchPath: module-server/src/main/resources/config
  kafka:
    host: kafka
    port: 9092

service:
  port: *applicationPort
  actuatorPort: *actuatorPort

environment:
  - name: PORT
    value: "{{ .Values.application.port }}"
  - name: ACTUATOR_PORT
    value: "{{ .Values.application.actuatorPort }}"
  - name: PREFIX
    value: "{{ .Values.application.prefix }}"
  - name: REPOSITORY_PATH
    value: "{{ .Values.application.repositoryPath }}"
  - name: SEARCH_PATH
    value: "{{ .Values.application.searchPath }}"
  - name: KAFKA_HOST
    value: "{{ .Values.application.kafka.host }}"
  - name: KAFKA_PORT
    value: "{{ .Values.application.kafka.port }}"
