apiVersion: v2
name: routing
description: Installs the Routing backend into the Kubernetes cluster
type: application
version: 0.1.0
maintainers:
  - name: Jim Martens
    url: https://2martens.de
sources:
  - https://github.com/HBTGmbH/hackathon-2024-kotlin
dependencies:
  - name: template
    version: 0.5.0
    repository: file://../template
annotations:
  artifacthub.io/images: |
    - name: hbt/routing:latest
      image: hbt/routing:latest
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/changes: |
    - kind: added
      description: Added Routing Assistant chart
  artifacthub.io/signKey: |
    fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
    url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
  artifacthub.io/prerelease: true
