{{- define "template.leaderRole" -}}
{{- if .Values.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-role
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete
    resources:
      - configmaps
    apiGroups:
      - ""
  - verbs:
      - get
      - watch
      - list
    resources:
      - pods
    apiGroups:
      - ""
{{ end }}
{{ end }}
---
{{- define "template.leaderRoleBinding" -}}
{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  name: leader-role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
subjects:
  - kind: ServiceAccount
    name: {{ include "template.serviceAccountName" . }}
{{- end }}
{{- end }}