{{- define "template.secret" -}}
{{- if and .Values.secrets (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
  annotations:
    {{- include "template.annotations" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end}}
{{- end }}
{{- end }}
