{{- define "template.secret" -}}
{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  {{- with .Values.secrets }}
  {{- toYaml . | b64enc | nindent 2 }}
  {{- end}}
{{- end }}
{{- end }}
