{{- define "template.serviceAccount" -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template.serviceAccountName" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- include "template.annotations" . | nindent 4 }}
{{- end }}
{{- end }}
