image:
  repository: confluentinc/cp-zookeeper
  tag: latest
application:
  port: 2181
  isSpring: false
  tickTime: 2000
service:
  port: 2181
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
prometheus:
  enabled: false
environment:
  - name: ZOOKEEPER_CLIENT_PORT
    value: "{{ .Values.application.port }}"
  - name: ZOOKEEPER_TICK_TIME
    value: "{{ .Values.application.tickTime }}"
volumes:
  - name: kafka
    emptyDir:
      medium: Memory
  - name: log
    emptyDir:
      medium: Memory
volumeMounts:
  - mountPath: /etc/kafka
    name: kafka
  - mountPath: /var/log/kafka
    name: log
