---
- name: Create server
  hosts: setup
  gather_facts: false
  roles:
    - server_setup
- name: Set up domain
  hosts: frontend
  gather_facts: false
  remote_user: "{{ ssh_user }}"
  roles:
    - frontend
- name: Set up Spring Boot applications
  hosts: springBoot
  gather_facts: false
  become: true
  become_method: ansible.builtin.sudo
  remote_user: "{{ ssh_user }}"
  roles:
    - spring_boot
