---
- name: Create server
  hosts: setup
  gather_facts: false
  roles:
    - server_setup
- name: Set up drone
  hosts: ci
  gather_facts: false
  become: true
  become_method: ansible.builtin.sudo
  remote_user: "{{ ssh_user }}"
  roles:
    - drone
- name: Set up Gitea
  hosts: git
  gather_facts: false
  remote_user: "{{ ssh_user }}"
  roles:
    - gitea
