---
- name: Create server
  hosts: setup
  gather_facts: false
  serial: 1
  roles:
    - server_setup
- name: Set up frontend domains
  hosts: frontend
  gather_facts: false
  remote_user: "{{ ssh_user }}"
  roles:
    - frontend
- name: Set up devops server
  hosts: ci
  remote_user: "{{ ssh_user }}"
  roles:
    - apache
    - letsencrypt
    - docker
- name: Set up Drone
  hosts: ci
  become: true
  become_method: ansible.builtin.sudo
  remote_user: "{{ ssh_user }}"
  tags: drone
  roles:
    - drone
- name: Set up Gitea
  hosts: git
  gather_facts: false
  remote_user: "{{ ssh_user }}"
  roles:
    - gitea
- name: Set up application server
  hosts: applications
  become: true
  become_method: ansible.builtin.sudo
  remote_user: "{{ ssh_user }}"
  roles:
    - drone_accessible
    - docker
    - nginx
    - letsencrypt
    - kafka
- name: Set up Spring Boot applications
  hosts: applications
  become: true
  become_method: ansible.builtin.sudo
  remote_user: "{{ ssh_user }}"
  tags: springBoot
  roles:
    - spring_boot
