---
- name: Create SSH key
  hetzner.hcloud.ssh_key:
    api_token: "{{ server_setup_hcloud_api_token }}"
    public_key: "{{ server_setup_ssh_key_admin_user }}"
    name: "{{ server_setup_ssh_key_admin_user_name }}"
    state: present
- name: Create server via HCloud
  hetzner.hcloud.server:
    api_token: "{{ server_setup_hcloud_api_token }}"
    firewalls:
      - "{{ server_setup_basic_firewall }}"
    image: "{{ server_setup_server_image }}"
    location: "{{ server_setup_server_location }}"
    name: "{{ server_setup_server_name }}"
    placement_group: "{{ server_setup_server_placement_group }}"
    server_type: "{{ server_setup_server_type }}"
    ssh_keys:
      - "{{ server_setup_ssh_key_admin_user_name }}"
    user_data: "{{ lookup('ansible.builtin.template', 'basic-ssh-hardening.yaml.j2', convert_data=false) }}"
    state: present
  register: server
