{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: argocd-server-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.gateway.certIssuer }}
spec:
  gatewayClassName: cilium
  listeners:
    - name: {{ tpl (quote .Values.gateway.host) . }}
      protocol: HTTPS
      port: 443
      hostname: {{ tpl (quote .Values.gateway.host) . }}
      tls:
        certificateRefs:
          - kind: Secret
            name: argocd-server-tls
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-server-route
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - {{ tpl (quote .Values.gateway.host) . }}
  parentRefs:
    - name: cilium-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argo-cd-argocd-server
          port: https
{{- end }}
