{{- if .Values.cilium.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd
  namespace: {{ .Release.Namespace }}
specs:
  - endpointSelector:
      # apply to core dns pods
      matchLabels:
        app.kubernetes.io/name: argocd-server
    ingress:
      # kubelet -> probes
      - fromEntities:
          - world
        toPorts:
          - ports:
              - port: '8080'
                protocol: TCP
      # ingress -> server
      - fromEndpoints:
          - matchLabels:
              io.cilium.k8s.policy.serviceaccount: nginx-ingress-microk8s-serviceaccount
              io.kubernetes.pod.namespace: ingress
        toPorts:
          - ports:
              - port: '8080'
                protocol: TCP
      # prometheus -> server metrics
      - fromEndpoints:
          - matchLabels:
              io.cilium.k8s.policy.serviceaccount: prometheus-kube-prometheus-prometheus
              io.kubernetes.pod.namespace: observability
        toPorts:
          - ports:
              - port: '8083'
                protocol: TCP
    egress:
      - toEndpoints:
          - matchLabels:
              app.kubernetes.io/name: argocd-redis
        toPorts:
          - ports:
              - port: '6379'
                protocol: TCP
      - toEntities:
          - world
        toPorts:
          - ports:
              - port: '53'
                protocol: UDP
              - port: '443'
                protocol: TCP
  - endpointSelector:
      # apply to core dns pods
      matchLabels:
        app.kubernetes.io/name: argocd-application-controller
    ingress:
      # kubelet -> probes
      - fromEntities:
          - world
        toPorts:
          - ports:
              - port: '8082'
                protocol: TCP
  - endpointSelector:
      # apply to core dns pods
      matchLabels:
        app.kubernetes.io/name: argocd-repo-server
    ingress:
      # kubelet -> probes
      - fromEntities:
          - world
        toPorts:
          - ports:
              - port: '8081'
                protocol: TCP
              - port: '8084'
                protocol: TCP
{{- end }}