---
- name: Determine postgresql version
  ansible.builtin.command:
    cmd: uberspace tools version show postgresql
  register: active_postgresql_version
  changed_when: false
- name: Set used postgresql version
  ansible.builtin.command:
    cmd: uberspace tools version use postgresql {{ postgresql_version }}
  changed_when: true
  when: active_postgresql_version.stdout.find(postgresql_version) == -1
- name: Extend bash profile
  ansible.builtin.import_tasks: profile.yaml
- name: Check if postgresql database is created
  ansible.builtin.stat:
    path: ~/opt/postgresql/data
  register: postgresql_dir
- name: Set up postgresql
  when: not postgresql_dir.stat.exists
  ansible.builtin.import_tasks: setup.yaml
- name: Set up service
  ansible.builtin.import_tasks: service.yaml