apiVersion: v2
name: prometheus-adapter
version: 0.1.0
type: application
dependencies:
  - name: prometheus-adapter
    version: 4.7.1
    repository: https://prometheus-community.github.io/helm-charts